name: build-for-land

on: workflow_dispatch

jobs:
  build-for-land:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up Build Directories
        run: |
          mkdir ~/bin
          #export PATH=~/bin:$PATH
          mkdir -p ~/android/lineage
          cd ~/android/lineage
          
      - name: Installing Dependencies from Apt
        run: |
          sudo apt-get install openjdk-8-jdk libwxgtk3.0-gtk3-dev bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git curl
          
      - name: Installing "repo" Tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          
      - name: Authenticating "repo" with GitHub Account
        run: |
          git config --global user.email "banyaltanishq@gmail.com"
          git config --global user.name "Tanishq-Banyal"
          
      - name: Enabling Caching (not sure)
        run: |
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M 25G
          
      - name: Setting Up Local Repo
        run: |
          ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-16.0
          ~/bin/repo sync 
          git clone https://github.com/Chippa-a/android_device_sony_kugo device/sony/kugo
          git clone https://github.com/Chippa-a/android_kernel_sony_msm8956 kenrel/sony/msm8956
          git clone https://github.com/MaxRegner/proprietary_vendor_sony vendor/sony
          
      - name: Setting Up Build Environment
        run: |
          source build/envsetup.sh && breakfast land
          
      - name: Starting Build Process
        run: |
          croot && breakfast kugo
      
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: DD-MM-YYYY
      
      - name: Uploading Build to Releases
        uses: softprops/action-gh-release@v1
        with:
          name: "Auto Build ${{ steps.current-time.outputs.formattedTime }}"
          tag_name: v1.0
          prerelease: false
          body: |
            This is an Automatic Release by GitHub Actions.
          files: |
            $OUT/recovery.img
            $OUT/lineage-*-land.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
